#!/bin/bash
lock() {
    #scrot -e 'convert -blur 0x3 $f ~/.i3/lockbg.png'
    #convert -gravity center -composite ~/.i3/lock.png ~/.i3/lockfg.png ~/.i3/lockfinal.png
    i3lock -i ~/.i3/lockfinal.png \
        --insidecolor=00000000 \
        --insidevercolor=00000000 \
        --ringvercolor=FFFF00FF \
        --ringwrongcolor=FF0000FF \
        --insidewrongcolor=FF000000 \
        --textcolor=00000000
}

case "$1" in
    lock)
        lock
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
